### PR TITLE
fix quicklook preview

### PR DESCRIPTION
**Pull request by drselump14**
quicklook preview doesnt work, so I fix it using quicklookurl attributes provided by Alfred 3

### CODE REVIEW

**Comment by ethan-funny** [comment]
I try your solution, however, the quicklook preview doesn't work. The error shows below. So, do you have any idea?

Imgur

**Comment by drselump14** [comment]
are you using alfred 3?it only works for alfred 3..

**Comment by drselump14** [comment]
sorry,, I think i forgot to define the quicklook parameter in Item class constructor... it should work right now

**Comment by ethan-funny** [comment]
Yeah, I figure it out later, it works! Thanks!

**Review by ethan-funny — APPROVED** [review]

**Pull request merged**
